language: generic 
sudo: required

services: 
  - docker

before_install:
  - docker build -t smadaan2/react-test -f ./client/Dockerfile.dev ./client

#Due to a change in how the Jest library works with Create React App
#primarly test running section
script: 
  - docker run smadaan2/react-test npm test -- --coverage

after_success:
  - docker build -t smadaan2/multi-client ./client
  - docker build -t smadaan2/multi-nginx ./nginx
  - docker build -t smadaan2/multi-server ./server
  - docker build -t smadaan2/multi-worker ./worker

 #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 #Push the images to docker hub
  - docker push smadaan2/multi-client
  - docker push smadaan2/multi-nginx
  - docker push smadaan2/multi-server
  - docker push smadaan2/multi-worker

 # setting up elasticbean connection 
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-020122258339
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"   